<script lang="ts">
	import { ArrowLeftIcon } from '@lucide/svelte';
	import Content from '../../../components/content.svelte';

	let { data } = $props();
</script>

<svelte:head>
	<title>{data.article.title} - explore - aelpxy</title>
	<meta name="description" content={data.article.summary} />

	<meta property="og:type" content="article" />
	<meta property="og:url" content="https://aelpxy.dev/explore/{encodeURIComponent(data.topic)}" />
	<meta property="og:title" content="{data.article.title} - explore - aelpxy" />
	<meta property="og:description" content={data.article.summary} />
	<meta property="og:site_name" content="aelpxy" />
	<meta property="og:image" content="https://aelpxy.dev/og-image.png" />

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="{data.article.title} - explore - aelpxy" />
	<meta name="twitter:description" content={data.article.summary} />
</svelte:head>

<Content title="infinite explorer">
	<section class="text-md px-0 py-6 sm:py-8">
		<a
			href="/explore"
			class="mb-6 inline-flex items-center gap-1.5 text-sm text-neutral-500 transition-colors hover:text-neutral-300"
		>
			<ArrowLeftIcon size={14} />
			back to search
		</a>

		<article class="space-y-4">
			<div>
				<h2 class="text-2xl font-medium tracking-tight text-neutral-100">
					{data.article.title}
				</h2>
				<p class="mt-1 text-sm text-neutral-500">{data.article.readingTime}</p>
			</div>
			<p class="text-base text-neutral-400 italic">
				{data.article.summary}
			</p>
			{#if data.article.infobox && data.article.infobox.length > 0}
				<div
					class="grid grid-cols-2 gap-x-6 gap-y-2 rounded-lg border border-neutral-800 bg-neutral-900/30 px-4 py-3 sm:grid-cols-4"
				>
					{#each data.article.infobox as item (item.label)}
						<div>
							<dt class="text-xs text-neutral-500">{item.label}</dt>
							<dd class="text-sm text-neutral-300">{item.value}</dd>
						</div>
					{/each}
				</div>
			{/if}
			<div
				class="prose max-w-none prose-invert prose-headings:text-neutral-200 prose-p:text-neutral-300 prose-strong:text-neutral-200 prose-li:text-neutral-300"
			>
				{@html data.article.contentHtml}
			</div>
		</article>

		<div class="mt-8 border-t border-neutral-800 pt-6">
			<p class="mb-4 text-sm text-neutral-500">Continue exploring:</p>
			<div class="flex flex-wrap gap-2">
				{#each data.article.relatedTopics as topic (topic)}
					<a
						href="/explore/{encodeURIComponent(topic)}"
						class="rounded-lg border border-neutral-800 bg-neutral-900/50 px-3 py-2 text-sm text-neutral-400 transition-colors hover:border-neutral-700 hover:bg-neutral-800 hover:text-neutral-100"
					>
						{topic}
					</a>
				{/each}
			</div>
		</div>

		<div class="mt-12 border-t border-neutral-800 pt-6">
			<p class="text-sm text-neutral-500">
				Articles are generated by AI and may contain inaccuracies. For factual information, please
				verify with reliable sources.
			</p>
		</div>
	</section>
</Content>
