<script lang="ts">
	import { goto } from '$app/navigation';
	import { SearchIcon, ShuffleIcon } from '@lucide/svelte';
	import Content from '../../components/content.svelte';

	let searchInput = $state('');

	const topics = [
		'Quantum Computing',
		'Neural Networks',
		'Black Holes',
		'DNA Replication',
		'Game Theory',
		'Cryptography',
		'Chaos Theory',
		'Fractals',
		'Stoicism',
		'Dark Matter',
		'Neuroplasticity',
		'Time Dilation',
		'Entropy',
		'Symbiosis'
	];

	function explore(topic: string) {
		goto(`/explore/${encodeURIComponent(topic)}`);
	}

	function exploreRandom() {
		explore(topics[Math.floor(Math.random() * topics.length)]);
	}

	function handleSubmit(e: Event) {
		e.preventDefault();
		if (searchInput.trim()) explore(searchInput.trim());
	}
</script>

<svelte:head>
	<title>infinite explorer - aelpxy</title>
	<meta name="description" content="explore any topic with AI-generated Wikipedia-style articles" />

	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://aelpxy.dev/explore" />
	<meta property="og:title" content="infinite explorer - aelpxy" />
	<meta
		property="og:description"
		content="explore any topic with AI-generated Wikipedia-style articles"
	/>
	<meta property="og:site_name" content="aelpxy" />
	<meta property="og:image" content="https://aelpxy.dev/og-image.png" />
	<meta property="og:image:width" content="1200" />
	<meta property="og:image:height" content="630" />

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:url" content="https://aelpxy.dev/explore" />
	<meta name="twitter:title" content="infinite explorer - aelpxy" />
	<meta
		name="twitter:description"
		content="explore any topic with AI-generated Wikipedia-style articles"
	/>
	<meta name="twitter:image" content="https://aelpxy.dev/og-image.png" />

	<link rel="canonical" href="https://aelpxy.dev/explore" />
</svelte:head>

<Content title="infinite explorer">
	<section class="text-md px-0 py-6 sm:py-8">
		<div class="mt-2 text-base font-light text-neutral-300 sm:text-xl">
			<p class="text-xl tracking-tight">
				explore any topic endlessly. click any word to dive deeper.
			</p>
		</div>

		<div class="mt-8">
			<form onsubmit={handleSubmit} class="flex gap-2">
				<div class="relative flex-1">
					<SearchIcon size={18} class="absolute top-1/2 left-3 -translate-y-1/2 text-neutral-500" />
					<input
						type="text"
						bind:value={searchInput}
						placeholder="Enter a topic to explore..."
						class="w-full rounded-lg border border-neutral-800 bg-neutral-900 py-3 pr-4 pl-10 text-sm text-neutral-100 placeholder-neutral-600 transition-colors outline-none focus:border-neutral-700"
					/>
				</div>
				<button
					type="submit"
					disabled={!searchInput.trim()}
					class="rounded-lg bg-neutral-800 px-4 py-3 text-sm text-neutral-100 transition-colors hover:bg-neutral-700 disabled:opacity-50"
				>
					Explore
				</button>
				<button
					type="button"
					onclick={exploreRandom}
					class="flex items-center gap-2 rounded-lg border border-neutral-800 px-4 py-3 text-sm text-neutral-400 transition-colors hover:border-neutral-700 hover:bg-neutral-800 hover:text-neutral-100"
					title="Explore a random topic"
				>
					<ShuffleIcon size={16} />
					<span class="hidden sm:inline">Random</span>
				</button>
			</form>
		</div>

		<div class="mt-8">
			<p class="mb-4 text-sm text-neutral-500">Or start with a suggestion:</p>
			<div class="flex flex-wrap gap-2">
				{#each topics as topic (topic)}
					<a
						href="/explore/{encodeURIComponent(topic)}"
						class="rounded-lg border border-neutral-800 bg-neutral-900/50 px-3 py-2 text-sm text-neutral-300 transition-colors hover:border-neutral-700 hover:bg-neutral-800"
					>
						{topic}
					</a>
				{/each}
			</div>
		</div>

		<div class="mt-12 border-t border-neutral-800 pt-6">
			<p class="text-sm text-neutral-500">
				Articles are generated by AI and may contain inaccuracies. For factual information, please
				verify with reliable sources.
			</p>
		</div>
	</section>
</Content>
